services:
  - type: web
    name: umami
    env: docker
    repo: https://github.com/thomascenni/umami.git
    region: oregon # optional (defaults to oregon)
    plan: free
    branch: main
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: umami-db
          property: connectionString
      - key: HASH_SALT
        generateValue: true

databases:
  - name: umami-db
    plan: free
    databaseName: umami
    user: umami
